### ISSUE TITLE
about the learning parameters

### ISSUE THREAD

**Issue by caolusg** [hans/nn-decoding#1]
Hi,

Can you please provide the learn_decoder.py parameters, I tried few times but fail to run the learn_decoder.py

Thank you

**Comment by hans** [comment]
Hi Cao — we already spoke by email, but just for the public record:
You can find parameters for retraining the relevant decoder models in our CCN paper using the script [`learn_decoders.sh`](https://github.com/hans/nn-decoding/blob/857b74fb5b0786a8ee1abb88729b0a99d5ca84ff/scripts/learn_decoders.sh).
